apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
  labels:
    app: grafana
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn }}