global:
  team: ubuntu
  environment: dev

namespace:
  create: true
  name: eks-monitoring-dev

grafana:
  enabled: true
  image: grafana/grafana:11.1.0
  replicas: 1
  serviceAccountName: grafana
  service:
    port: 3000

  datasources:
    enabled: true
    prometheus:
      url: "http://eks-monitoring-dev-prometheus:9090"
    
  ingress:
    enabled: true
    className: nginx
    host: grafana-ubuntu-dev.312ubuntu.com
    tlsSecretName: wildcard-312ubuntu-tls

prometheus:
  enabled: true
  image: prom/prometheus:v2.52.0
  replicas: 1

  service:
    type: ClusterIP
    port: 9090

secretsManager:
  enabled: true
  name: "grafana-admin-spc"
  secretName: "eks-monitoring/grafana-admin"
  irsaRoleArn: "arn:aws:iam::383585068161:role/eks-monitoring-grafana-irsa"