apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRole.name }}
  labels:
    environment: {{ .Values.environment }}
rules:
- apiGroups: [""]
  resources:
    - pods
    - services
    - configmaps
    - endpoints
    - persistentvolumeclaims
    - events
  verbs: ["get", "watch", "list", "describe"]

- apiGroups: ["apps"]
  resources:
    - deployments
    - replicasets
    - statefulsets
  verbs: ["get", "watch", "list", "describe"]
