{{- if and .Values.grafana.enabled .Values.secretsManager.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "grafana" .Values.grafana.serviceAccountName }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.secretsManager.irsaRoleArn | quote }}
{{- end }}