{{- if and .Values.grafana.enabled .Values.secretsManager.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretsManager.name | quote }}
  namespace: {{ .Values.namespace.name }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.secretsManager.secretName | quote }}
        objectType: "secretsmanager"
        jmesPath:
          - path: admin-user
            objectAlias: admin-user
          - path: admin-password
            objectAlias: admin-password
{{- end }}
