# Dev environment values — single replica, no persistence, security off

global:
  environment: dev

elasticsearch:
  replicas: 1
  javaOpts: "-Xmx512m -Xms512m"
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi
  antiAffinity: ""
  pdb:
    enabled: false
  security:
    enabled: false
