{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.namespace.name }}-elasticsearch-config
  namespace: {{ .Values.namespace.name }}
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |
    cluster.name: {{ .Values.elasticsearch.clusterName }}
    network.host: 0.0.0.0

    discovery.seed_hosts:
      - {{ .Values.namespace.name }}-elasticsearch-headless
    cluster.initial_master_nodes:
      {{- $namespaceName := .Values.namespace.name }}
      {{- $replicas := int .Values.elasticsearch.replicas }}
      {{- range $i := until $replicas }}
      - {{ $namespaceName }}-elasticsearch-{{ $i }}
      {{- end }}

    {{- if .Values.elasticsearch.security.enabled }}
    xpack.security.enabled: true
    {{- if .Values.elasticsearch.security.transportSsl }}
    xpack.security.transport.ssl.enabled: true
    xpack.security.transport.ssl.verification_mode: certificate
    {{- else }}
    xpack.security.transport.ssl.enabled: false
    {{- end }}
    {{- else }}
    xpack.security.enabled: false
    {{- end }}
{{- end }}
