global:
  team: ubuntu
  environment: dev

namespace:
  create: true
  name: eks-monitoring

prometheus:
  enabled: true
  image: prom/prometheus:v2.52.0
  replicas: 1

  service:
    type: ClusterIP
    port: 9090

  resources: {}

kubeStateMetrics:
  enabled: true
  image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.12.0
  replicas: 1

nodeExporter:
  enabled: true
  image: prom/node-exporter:v1.8.1

grafana:
  enabled: false
  image: grafana/grafana:11.1.0
  replicas: 1

  service:
    port: 3000

  ingress:
    enabled: false
    className: nginx
    host: ""
    whitelistSourceRange: "98.212.25.205/32"
    tlsSecretName: wildcard-312ubuntu-tls

  admin:
    existingSecretName: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

  datasources:
    enabled: true
