apiVersion: v2
name: helm-kibana
description: Kibana dashboard for Elasticsearch on Amazon EKS
type: application
version: 1.0.0
appVersion: "8.5.1"
keywords:
  - logging
  - kibana
  - efk
  - eks
maintainers:
  - name: ubuntu-team
