{{- if and .Values.fluentd.enabled .Values.fluentd.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fluentd.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: fluentd
  {{- if .Values.aws.accountId }}
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ toString .Values.aws.accountId }}:role/fluentd-s3-{{ .Values.global.environment }}"
  {{- end }}
{{- end }}
