{{- if and .Values.kibana.enabled .Values.kibana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.namespace.name }}-kibana-ingress
  namespace: {{ .Values.namespace.name }}
  labels:
    app: kibana
  annotations:
    {{- if .Values.kibana.ingress.whitelistSourceRange }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.kibana.ingress.whitelistSourceRange | quote }}
    {{- end }}
    {{- if .Values.kibana.ingress.authSecret }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.kibana.ingress.authSecret }}
    nginx.ingress.kubernetes.io/auth-realm: {{ .Values.kibana.ingress.authRealm | quote }}
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.kibana.ingress.sslRedirect | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.kibana.ingress.proxyBodySize | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.kibana.ingress.proxyReadTimeout | quote }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.kibana.ingress.proxySendTimeout | quote }}
    {{- if .Values.kibana.ingress.host }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.kibana.ingress.host }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.kibana.ingress.className }}
  {{- if .Values.kibana.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.kibana.ingress.host }}
      secretName: {{ .Values.kibana.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.kibana.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.namespace.name }}-kibana
                port:
                  number: {{ .Values.kibana.service.port }}
{{- end }}
