global:
  team: ubuntu
  environment: dev

namespace:
  create: true
  name: eks-monitoring-dev

prometheus:
  enabled: true
  image: prom/prometheus:v2.52.0
  replicas: 1

  service:
    type: ClusterIP
    port: 9090

  resources: {}

kubeStateMetrics:
  enabled: true
  image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.12.0
  replicas: 1
  
nodeExporter:
  enabled: true
  image: prom/node-exporter:v1.8.1

grafana:
  enabled: true
  admin: 
    user: admin
    password: ChangeMe-Strong123!

  ingress:
    enabled: true
    className: nginx
    host: grafana-ubuntu-dev.312ubuntu.com
    tlsSecretName: wildcard-312ubuntu-tls
    whitelistSourceRange: "98.212.25.205/32"
