{{- if and .Values.elasticsearch.enabled .Values.elasticsearch.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "eks-logging.componentName" (dict "component" "elasticsearch" "context" $) }}
  namespace: {{ include "eks-logging.namespace" . }}
  labels:
    {{- include "eks-logging.elasticsearchLabels" (dict "context" $) | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.elasticsearch.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "eks-logging.selectorLabels" (dict "component" "elasticsearch" "context" $) | nindent 6 }}
{{- end }}
