{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eks-logging.componentName" (dict "component" "elasticsearch-headless" "context" $) }}
  namespace: {{ include "eks-logging.namespace" . }}
  labels:
    {{- include "eks-logging.elasticsearchLabels" (dict "context" $) | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: {{ .Values.elasticsearch.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: transport
      port: {{ .Values.elasticsearch.service.transportPort }}
      targetPort: transport
      protocol: TCP
  selector:
    {{- include "eks-logging.selectorLabels" (dict "component" "elasticsearch" "context" $) | nindent 4 }}
{{- end }}
