{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eks-logging.componentName" (dict "component" "elasticsearch" "context" $) }}-config
  namespace: {{ include "eks-logging.namespace" . }}
  labels:
    {{- include "eks-logging.elasticsearchLabels" (dict "context" $) | nindent 4 }}
data:
  elasticsearch.yml: |
    cluster.name: {{ .Values.elasticsearch.clusterName }}
    network.host: 0.0.0.0

    discovery.seed_hosts:
      - {{ include "eks-logging.componentName" (dict "component" "elasticsearch-headless" "context" $) }}
    cluster.initial_master_nodes:
      {{- $releaseName := .Release.Name }}
      {{- $replicas := int .Values.elasticsearch.replicas }}
      {{- range $i := until $replicas }}
      - {{ $releaseName }}-elasticsearch-{{ $i }}
      {{- end }}

    {{- if .Values.elasticsearch.security.enabled }}
    xpack.security.enabled: true
    {{- if .Values.elasticsearch.security.transportSsl }}
    xpack.security.transport.ssl.enabled: true
    xpack.security.transport.ssl.verification_mode: certificate
    {{- else }}
    xpack.security.transport.ssl.enabled: false
    {{- end }}
    {{- else }}
    xpack.security.enabled: false
    {{- end }}
{{- end }}
