{{- if and .Values.kibana.enabled .Values.kibana.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "eks-logging.componentName" (dict "component" "kibana" "context" $) }}
  namespace: {{ include "eks-logging.namespace" . }}
  labels:
    {{- include "eks-logging.kibanaLabels" (dict "context" $) | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.kibana.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "eks-logging.selectorLabels" (dict "component" "kibana" "context" $) | nindent 6 }}
{{- end }}
