{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "eks-logging.namespace" . }}
  labels:
    {{- include "eks-logging.commonLabels" . | nindent 4 }}
{{- end }}
