#FOR TEST PURPUSES ONLY

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dns-test
spec:
  ingressClassName: nginx
  rules:
    - host: dns-test.312ubuntu.com # change to dns-test.dev.312ubuntu.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dns-test
                port:
                  number: 80
