# values.yaml

# Environment info
environment:
  name: dev   # can be dev, staging, prod

# Cluster info
cluster:
  name: dev-cluster
  region:
    name: us-east-1

# ClusterRole info
ClusterRole:
  name: read-access-role

# ClusterRoleBinding info
ClusterRBAC:
  name: read-access-binding

# Kubernetes Group info
Group:
  name: developers

# IAM Role mapping for eksctl
iamIdentityMappings:
  - arn: arn:aws:iam::123456789012:role/EKS-Dev
    username: dev-user
    groups:
      - developers

