global:
  imagePullSecrets: []

image:
  repository: registry.k8s.io/external-dns/external-dns
  pullPolicy: IfNotPresent 

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::383585068161:role/dev-temp-eks-cluster-external-dns-irsa
  name: external-dns
  automountServiceAccountToken: true

service:
   port: 7979 

rbac: 
  create: true

deploymentStrategy: 
  type: Recreate 

automountServiceAccountToken: true

shareProcessNamespace: false

podSecurityContext:
  runAsNonRoot: true
  fsGroup: 65534
  seccompProfile:
    type: RuntimeDefault

securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  capabilities:
    drop: ["ALL"]

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

serviceMonitor:
  enabled: false
  interval: 1m 

logLevel: info 

logFormat: text 

interval: 1m

triggerLoopOnEvent: false

namespaced: false

sources:
  - ingress

policy: sync 

registry: txt 

txtOwnerId: temp-eks-cluster 

txtPrefix: external-dns- 

annotationFilter: external-dns.alpha.kubernetes.io/hostname

# -- Annotation prefix for external-dns annotations (useful for split horizon DNS with multiple instances).
annotationPrefix: # @schema type: [string,null]; default: null

provider: 
  name: aws
  webhook:
    image:
      pullPolicy: IfNotPresent
    livenessProbe:
      httpGet:
        path: /healthz 
        port: http-webhook 
      initialDelaySeconds: 10 
      periodSeconds: 10 
      timeoutSeconds: 5 
      failureThreshold: 2 
      successThreshold: 1 
    
    readinessProbe:
      httpGet:
        path: /healthz 
        port: http-webhook 
      initialDelaySeconds: 5 
      periodSeconds: 10 
      timeoutSeconds: 5 
      failureThreshold: 6 
      successThreshold: 1 
    service:
      port: 8080
    
    serviceMonitor:
      interval: 1m 

extraArgs:
  - --zone-id-filter=Z09469413H61XF9MA5W6E

secretConfiguration:
  enabled: false