---
name: "Workflow - Deploy External DNS to EKS Cluster"

"on":
  push:
    branches:
      - feature/MRP25BUBUN-9-external-dns

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"

jobs:
  deploy-platform-tools:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          role-session-name: GitHubActionsRoleSession
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      # Login to EKS, make sure to switch to the permanent cluster created with terraform once it's up
      - name: Login to EKS - update kubeconfig
        run: >
          aws eks update-kubeconfig
          --name temp-eks-cluster
          --region $AWS_REGION

      - name: Deploy external-dns (Helm)  # deploy from LOCAL chart + local values
        run: |
          helm lint external-dns/external-dns-helm  # validate chart
          helm upgrade --install external-dns external-dns/external-dns-helm \
            --namespace external-dns \
            -f external-dns/external-dns-helm/values.yaml \
            --rollback-on-failure \

      - name: Verify external-dns rollout  # make sure pods are healthy
        run: |
          kubectl get pods -n external-dns
          kubectl rollout status deploy/external-dns \
            -n external-dns \
            --timeout=180s
