---
name: "Workflow - Perform Automated Tests for External DNS"

on:
  push:
    branches:
      - feature/MRP25BUBUN-9-external-dns

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"
  CLUSTER_NAME: "temp-eks-cluster"
  NAMESPACE: "external-dns"

jobs:
  deploy-external-dns:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          role-session-name: GitHubActionsRoleSession
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to EKS - update kubeconfig
        run: >
          aws eks update-kubeconfig
          --name $CLUSTER_NAME
          --region $AWS_REGION

      - name: Install tooling for tests
        run: |
          sudo apt-get update
          sudo apt-get install -y dnsutils curl

      - name: Verify external-dns rollout
        run: |
          kubectl rollout status deployment/external-dns -n "$NAMESPACE" --timeout=180s
          kubectl get pods -n "$NAMESPACE" -l app.kubernetes.io/name=external-dns

      - name: Deploy deployment, service, and ingress
        env:
          TEST_NS: external-dns-test
        run: |
          kubectl get ns "$TEST_NS" >/dev/null 2>&1 || kubectl create ns "$TEST_NS"
          kubectl apply -f external-dns/integration-tests/dns-test-deploy.yaml
          kubectl apply -f external-dns/integration-tests/dns-test-ingress.yaml
          kubectl rollout status deploy/dns-test -n "$TEST_NS" --timeout=180s

      - name: Wait for DNS record + verify nslookup + curl
        env:
          TEST_FQDN: dns-test.312ubuntu.com
        run: |
          set -eu

          echo "Waiting for DNS: $TEST_FQDN"
          for i in {1..40}; do
            nslookup "$TEST_FQDN" >/dev/null 2>&1 && break
            echo "Not ready ($i/40)..."
            sleep 15
          done

          nslookup "$TEST_FQDN" >/dev/null 2>&1 || { echo "DNS FAILED"; exit 1; }
          echo "DNS OK"

          echo "Checking HTTP"
          curl -fsS "http://$TEST_FQDN" >/dev/null || { echo "HTTP FAILED"; exit 1; }
          echo "HTTP OK "

      - name: Cleanup sample resources
        if: always()
        env:
          TEST_NS: external-dns-test
        run: |
          kubectl delete -n "$TEST_NS" -f external-dns/integration-tests/dns-test-ingress.yaml --ignore-not-found=true
          kubectl delete -n "$TEST_NS" -f external-dns/integration-tests/dns-test-deploy.yaml --ignore-not-found=true
          kubectl delete ns "$TEST_NS" --ignore-not-found=true


